name: conectasoc
description: 'Portal para miembros de diferentes asociaciones'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.0.0 <4.0.0'

dependencies:
    cached_network_image: ^3.4.1
    cloud_firestore: ^6.1.2
    collection: ^1.19.1
    connectivity_plus: ^7.0.0
    crypto: ^3.0.7
    cupertino_icons: ^1.0.8
    dartz: ^0.10.1
    equatable: ^2.0.8
    firebase_analytics: ^12.1.1
    firebase_auth: ^6.1.4
    firebase_core: ^4.4.0
    firebase_messaging: ^16.1.1
    flutter:
        sdk: flutter
    flutter_bloc: ^9.1.1
    flutter_form_builder: ^10.3.0+1
    flutter_local_notifications: ^20.0.0
    flutter_localizations:
        sdk: flutter
    flutter_quill: ^11.5.0
    flutter_svg: ^2.2.3
    form_builder_validators: ^11.3.0
    get_it: ^9.2.0
    go_router: ^17.1.0
    http: ^1.6.0
    image: ^4.7.2
    image_cropper: ^11.0.0
    image_picker: ^1.2.1
    injectable: ^2.7.1+4
    intl: ^0.20.2
    logger: ^2.6.2
    path: ^1.9.1
    path_provider: ^2.1.5
    permission_handler: ^12.0.1
    photo_view: ^0.15.0
    rxdart: ^0.28.0
    shared_preferences: ^2.5.4
    translator: ^1.0.4+1
    tuple: ^2.0.2
    uuid: ^4.5.2

dev_dependencies:
    build_runner: ^2.10.5
    flutter_lints: ^6.0.0
    flutter_test:
        sdk: flutter
    injectable_generator: ^2.12.0
    json_annotation: ^4.10.0
    json_serializable: ^6.12.0

# Overrides for dependency conflicts.
# Use this section to force a specific version of a package.
dependency_overrides:
    intl: 0.20.2

flutter:
    generate: true # Activado para flutter gen-l10n
    uses-material-design: true

    assets:
        - assets/images/
        - assets/icons/
        - assets/logos/

    fonts:
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Regular.ttf
                weight: 400
              - asset: assets/fonts/Roboto-Bold.ttf
                weight: 700
